# Source: sonarqube-secrets/templates/sonarqube-secret.yaml
kind: "ExternalSecret"
apiVersion: "kubernetes-client.io/v1"
metadata:
  name: "sonarqube-credentials"
  namespace: "sonarqube"
  annotations:
    meta.helm.sh/release-name: 'sonarqube-secrets'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: "vault"
  data:
    - key: "secret/data/sonarqube"
      name: "sonarqube-password"
      property: "password"
    - key: "secret/data/postgres"
      name: "postgresql-password"
      property: "password"
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replication-allowed: "true"
        replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
    type: "Opaque"
  vaultMountPoint: "kubernetes"
  vaultRole: "jx-vault"
