# Source: harbor/templates/ingress/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "harbor-ingress"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: harbor
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: tls.crt
      key: secret/data/harbor/ingress
      property: tls.crt
    - name: tls.key
      key: secret/data/harbor/ingress
      property: tls.key
    - name: ca.crt
      key: secret/data/harbor/ingress
      property: ca.crt
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'harbor'
      labels:
        heritage: Helm
        release: harbor
        chart: harbor
        app: "harbor"
    type: kubernetes.io/tls
