apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - simonrowe
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: simonjamesrowe
    repository: jx3
  - key: staging
  - key: production
  ingress:
    domain: simonjamesrowe.com
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: "simon.rowe@gmail.com"
      enabled: true
      production: true
  pipelineUser:
    username: simonrowe
  repository: bucketrepo
  secretStorage: vault
  vault: {}
  webhook: lighthouse
