# Source: mongodb/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.30.6
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: mongodb-root-password
      key: secret/data/mongodb
      property: mongodb-root-password
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'mongodb'
      labels:
        app.kubernetes.io/name: mongodb
        helm.sh/chart: mongodb-10.30.6
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: mongodb
    type: Opaque
