# Source: mongodb/templates/pvc-standalone.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mongodb
    chart: mongodb-7.14.0
    heritage: Helm
    release: mongodb
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: mongodb
  namespace: mongodb
  annotations:
    meta.helm.sh/release-name: 'mongodb'
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
