# Source: mongodb/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
    chart: mongodb-7.14.0
    release: "mongodb"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: mongodb-root-password
      key: secret/data/mongodb
      property: mongodb-root-password
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'mongodb'
      labels:
        app: mongodb
        chart: mongodb-7.14.0
        release: "mongodb"
        heritage: "Helm"
    type: Opaque
