filepath: ""
environments: {}
namespace: mongodb
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
- chart: ./secrets
  version: 1.0.0
  name: mongo-secrets
  namespace: mongodb
- chart: bitnami/mongodb
  version: 10.30.6
  name: mongodb
  values:
  - values.yaml
templates: {}
renderedvalues: {}
