filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: mongodb
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
- chart: ./secrets
  version: 1.0.0
  name: mongo-secrets
  namespace: mongodb
  values:
  - jx-values.yaml
- chart: bitnami/mongodb
  version: 10.30.6
  name: mongodb
  values:
  - values.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}
