# Source: elastic-secrets/templates/tls.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "tls-simonjamesrowe-com-p"
  namespace: elastic
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: tls.crt
      key: secret/data/tls/simonjamesrowe/com/p
      property: tls.crt
    - name: tls.key
      key: secret/data/tls/simonjamesrowe/com/p
      property: tls.key
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replicate-from: jx/tls-simonjamesrowe-com-p
        meta.helm.sh/release-name: 'elastic-secrets'
    type: kubernetes.io/tls
