# Source: mongo-secrets/templates/mongo-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mongo-credentials
  namespace: mongodb
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'mongo-secrets'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: mongodb-password
      key: secret/data/mongodb
      property: password
    - name: mongodb-root-password
      key: secret/data/mongodb
      property: password
    - name: mongodb-replica-set-key
      key: secret/data/mongodb
      property: password
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replication-allowed: "true"
        replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
    type: Opaque
