filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: postgres
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
- chart: ./secrets
  version: 1.0.0
  name: postgres-secrets
  namespace: postgres
  values:
  - jx-values.yaml
- chart: bitnami/postgresql
  version: 10.13.15
  name: postgresql
  values:
  - values.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}
