# Source: harbor/templates/notary/notary-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-notary-server
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    component: notary-server
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'harbor'
    wave.pusher.com/update-on-config-change: 'true'
  namespace: harbor
spec:
  replicas: 1
  selector:
    matchLabels:
      release: harbor
      app: "harbor"
      component: notary-server
  template:
    metadata:
      labels:
        heritage: Helm
        release: harbor
        chart: harbor
        app: "harbor"
        component: notary-server
      annotations:
        checksum/secret: 4225b4763f46ff10f19a2a9210f2cdcb1fc5c6f2553d49053b4fe0e06009d017
        checksum/secret-core: 39d7c89bece585dd28e5f996670799c112eb80b3c0fad5303551c38e4faf5bcb
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      automountServiceAccountToken: false
      containers:
        - name: notary-server
          image: goharbor/notary-server-photon:v2.3.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /_notary_server/health
              scheme: "HTTP"
              port: 4443
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_notary_server/health
              scheme: "HTTP"
              port: 4443
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: MIGRATIONS_PATH
              value: migrations/server/postgresql
            - name: DB_URL
              value: postgres://postgres:changeit@harbor-database:5432/notaryserver?sslmode=disable
          volumeMounts:
            - name: config
              mountPath: /etc/notary/server-config.postgres.json
              subPath: server.json
            - name: token-service-certificate
              mountPath: /root.crt
              subPath: tls.crt
            - name: signer-certificate
              mountPath: /etc/ssl/notary/ca.crt
              subPath: ca.crt
      volumes:
        - name: config
          secret:
            secretName: "harbor-notary-server"
        - name: token-service-certificate
          secret:
            secretName: harbor-core
        - name: signer-certificate
          secret:
            secretName: harbor-notary-server
