# Source: harbor/templates/notary/notary-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: harbor-notary-signer
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'harbor'
  namespace: harbor
spec:
  ports:
    - port: 7899
  selector:
    release: harbor
    app: "harbor"
    component: notary-signer
