filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: kafka
repositories:
- name: confluent
  url: https://confluentinc.github.io/cp-helm-charts/
releases:
- chart: confluent/cp-helm-charts
  version: 0.6.0
  name: cp-helm-charts
  values:
  - values.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}
