cp-kafka:
  enabled: true
  brokers: 1

  configurationOverrides:
    "offsets.topic.replication.factor": "1"

  heapOptions: "-Xms256M -Xmx256M"

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
     limits:
      cpu: 100m
      memory: 400Mi
     requests:
      cpu: 100m
      memory: 500Mi


cp-zookeeper:
  ## If true, install the cp-zookeeper chart alongside cp-kafka
  ## ref: ../cp-zookeeper
  enabled: true
  servers: 1
  heapOptions: "-Xms128M -Xmx128M"
  persistence:
    enabled: false

cp-schema-registry:
  enabled: false

cp-kafka-rest:
  enabled: false

cp-kafka-connect:
  enabled: false

cp-ksql-server:
  enabled: false

cp-control-center:
  enabled: false

persistence:
  size: 10Gi