# Source: jx-secrets/templates/maven.yaml
kind: "ExternalSecret"
apiVersion: "kubernetes-client.io/v1"
metadata:
  name: "maven"
  namespace: "jx"
  annotations:
    meta.helm.sh/release-name: 'jx-secrets'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: "vault"
  data:
    - key: "secret/data/maven"
      name: "settings.xml"
      property: "settings.xml"
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replication-allowed: "true"
        replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
    type: "Opaque"
  vaultMountPoint: "kubernetes"
  vaultRole: "jx-vault"
