apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: simonjamesrowe
    provider: github
    repository: jenkinsx-buildpacks
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: simonjamesrowe-jenkinsx-buildpacks
  namespace: jx
spec:
  httpCloneURL: https://github.com/simonjamesrowe/jenkinsx-buildpacks.git
  org: simonjamesrowe
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jenkinsx-buildpacks
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/simonjamesrowe/jenkinsx-buildpacks
