apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: simonjamesrowe
    provider: github
    repository: demo-react
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: simonjamesrowe-demo-react
  namespace: jx
spec:
  httpCloneURL: https://github.com/simonjamesrowe/demo-react.git
  org: simonjamesrowe
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: demo-react
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/simonjamesrowe/demo-react
