# Source: sonarqube/templates/secret.yaml---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-sonarqube-monitoring-passcode
  labels:
    app: sonarqube
    chart: sonarqube-1.2.5_179
    release: sonarqube
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: sonarqube
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: SONAR_WEB_SYSTEMPASSCODE
      key: secret/data/sonarqube/sonarqube/monitoring/passcode
      property: SONAR_WEB_SYSTEMPASSCODE
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'sonarqube'
      labels:
        app: sonarqube
        chart: sonarqube-1.2.5_179
        release: sonarqube
        heritage: Helm
    type: Opaque
