# Source: sonarqube/templates/prometheus-ce-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-sonarqube-prometheus-ce-config
  labels:
    app: sonarqube
    chart: sonarqube-1.2.5_179
    release: sonarqube
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'sonarqube'
  namespace: sonarqube
data:
  prometheus-ce-config.yaml: |-
    rules:
    - pattern: .*
