# Source: harbor/templates/database/database-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "harbor-database"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: harbor
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: POSTGRES_PASSWORD
      key: secret/data/harbor/database
      property: POSTGRES_PASSWORD
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'harbor'
      labels:
        heritage: Helm
        release: harbor
        chart: harbor
        app: "harbor"
    type: Opaque
