apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: container-registry-auth
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: url
      key: secret/data/harbor/jx-registry
      property: url
    - name: username
      key: secret/data/harbor/jx-registry
      property: username
    - name: password
      key: secret/data/harbor/jx-registry
      property: password
  template:
    metadata:
    type: Opaque
