
apiVersion: v1
data:
  tls.crt: Zm9vIC1uCg==
  tls.key: Zm9vIC1uCg==
kind: Secret
metadata:
  annotations:
    replicator.v1.mittwald.de/replicate-from: jx/tls-simonjamesrowe-com-pp
  name: "tls-simonjamesrowe-com-p"
type: kubernetes.io/tls

