filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: sonarqube
repositories:
- name: sonarqube
  url: https://SonarSource.github.io/helm-chart-sonarqube
releases:
- chart: ./secrets
  version: 1.0.0
  name: sonarqube-secrets
  namespace: sonarqube
  values:
  - jx-values.yaml
- chart: sonarqube/sonarqube
  version: 1.2.5+179
  name: sonarqube
  values:
  - values.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}
