ingress:
  enabled: true
  hosts:
    - name: sonarqube.simonjamesrowe.com
  tls:
    - hosts:
        - sonarqube.simonjamesrowe.com
      secretName: tls-simonjamesrowe-com-p

jvmOpts: -Xms256m -Xmx512m
jvmCeOpts: -Xms256m -Xmx512m

resources:
  limits:
    cpu: 400m
    memory: 756Mi
  requests:
    cpu: 400m
    memory: 756Mi

jdbcOverwrite:
  enable: true
  jdbcUrl: jdbc:postgresql://postgresql.postgres:5432/control-plane?socketTimeout=1500
  jdbcUsername: postgres
  jdbcSecretName: sonarqube-credentials
  jdbcSecretPasswordKey: postgresql-password

postgresql:
  enabled: false


