existingSecret: sonarqube-credentials
ingress:
  enabled: true
  hostname: sonarqube.simonjamesrowe.com
  tls: false
  extraTls:
    hosts:
      - sonarqube.simonjamesrowe.com
    secretName: tls-simonjamesrowe-com-p
postgres:
  enabled: false
externalDatabase:
  host: postgresql.postgres
  existingSecret: sonarqube-credentials
  database: control-plane
  name: postgresql
