resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 200m
    memory: 512Mi
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
#    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
  path: /
  hosts:
    - kibana.simonjamesrowe.com
  tls:
    - secretName: tls-simonjamesrowe-com-p
      hosts:
        - kibana.simonjamesrowe.com