# Source: k8s-service/templates/customresources.yaml
apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    replicator.v1.mittwald.de/replicate-from: mongodb/mongo-credentials
    meta.helm.sh/release-name: 'cms'
  name: "mongo-credentials"
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
type: Opaque
