kind: "ExternalSecret"
apiVersion: "kubernetes-client.io/v1"
metadata:
  name: "sonarqube-credentials"
  namespace: "sonarqube"
spec:
  backendType: "vault"
  data:
  - key: "secret/data/sonarqube"
    name: "sonarqubeUsername"
    property: "username"
  - key: "secret/data/sonarqube"
    name: "sonarqubePassword"
    property: "password"
  - key: "secret/data/postgres"
    name: "postgresql-password"
    property: "password"
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replication-allowed: "true"
        replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
    type: "Opaque"
  vaultMountPoint: "kubernetes"
  vaultRole: "jx-vault"
