# Source: harbor/templates/core/core-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: harbor
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: secretKey
      key: secret/data/harbor/core
      property: secretKey
    - name: secret
      key: secret/data/harbor/core
      property: secret
    - name: tls.crt
      key: secret/data/harbor/core
      property: tls.crt
    - name: tls.key
      key: secret/data/harbor/core
      property: tls.key
    - name: HARBOR_ADMIN_PASSWORD
      key: secret/data/harbor/core
      property: HARBOR_ADMIN_PASSWORD
    - name: POSTGRESQL_PASSWORD
      key: secret/data/harbor/core
      property: POSTGRESQL_PASSWORD
    - name: REGISTRY_CREDENTIAL_PASSWORD
      key: secret/data/harbor/core
      property: REGISTRY_CREDENTIAL_PASSWORD
    - name: CSRF_KEY
      key: secret/data/harbor/core
      property: CSRF_KEY
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'harbor'
      labels:
        heritage: Helm
        release: harbor
        chart: harbor
        app: "harbor"
    type: Opaque
