---
kind: "ExternalSecret"
apiVersion: "kubernetes-client.io/v1"
metadata:
  creationTimestamp: "2021-12-13T07:09:36Z"
  generation: 1
  labels:
    gitops.jenkins-x.io/pipeline: "namespaces"
  name: "container-registry-auth"
  namespace: "jx"
  resourceVersion: "10017443"
  uid: "35f5d0de-f865-4479-a8a8-3c20db786974"
spec:
  backendType: "vault"
  data:
  - key: "secret/data/harbor/jx-registry"
    name: "url"
    property: "url"
  - key: "secret/data/harbor/jx-registry"
    name: "username"
    property: "username"
  - key: "secret/data/harbor/jx-registry"
    name: "password"
    property: "password"
  template:
    metadata: null
    type: "Opaque"
  vaultMountPoint: "kubernetes"
  vaultRole: "jx-vault"
