kind: "ExternalSecret"
apiVersion: "kubernetes-client.io/v1"
metadata:
  name: "gradle"
  namespace: "jx"
spec:
  backendType: "vault"
  data:
  - key: "secret/data/gradle"
    name: "init.gradle"
    property: "init.gradle"
  - key: "secret/data/gradle"
    name: "gradle.properties"
    property: "gradle.properties"
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replication-allowed: "true"
        replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
    type: "Opaque"
  vaultMountPoint: "kubernetes"
  vaultRole: "jx-vault"
