kind: "ExternalSecret"
apiVersion: "kubernetes-client.io/v1"
metadata:
  name: "maven"
  namespace: "jx"
spec:
  backendType: "vault"
  data:
  - key: "secret/data/maven"
    name: "settings.xml"
    property: "settings.xml"
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replication-allowed: "true"
        replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
    type: "Opaque"
  vaultMountPoint: "kubernetes"
  vaultRole: "jx-vault"
